### ISSUE TITLE
Is there a talk with this?

### ISSUE THREAD

**Issue by juddey** [GantMan/ReactStateMuseum#1]
I'm hoping that this repo will also (eventually) come with a wunderbar conference-recorded talk. What say you, savage?

**Comment by GantMan** [comment]
LOL, I'm thinking of it!  Definitely a blog post, but I can do this for my talk in React Native EU maybe....  
Or maybe submit it to somewhere else!  I'm still working on it for sure ;)

**Comment by juddey** [comment]
Cool! There are so many state solutions nowadays one wonders what the best one to choose is. More information is a good thing! :incoming_envelope:

**Comment by juddey** [comment]
Woot! Article has landed: :small_airplane: https://hackernoon.com/the-react-state-museum-a278c726315

**Comment by GantMan** [comment]
Now the hope there will be a talk?  We'll see :)

I feel the blog is dry compared to my in-person version, hahaha.
