### ISSUE TITLE
Update to React Native 0.58.3

### ISSUE THREAD

**Issue by marcelkalveram** [GantMan/ReactStateMuseum#115]
Stumbled upon this after listening to the RN podcast. Great job @GantMan, and really pleased to see so many examples in React Native.

I realised that many of them are still on RN 0.55 though, and it might make sense to upgrade them to 0.58.3 (the latest version) as many people (including me) are now on xCode 10 and 0.55 is throwing a lot of errors.

Happy to take care of this, but first wanted to make sure it's something the community is interested in.

**Comment by GantMan** [comment]
That would be epic!  The PR would definitely be appreciated.

**Comment by marcelkalveram** [comment]
@GantMan cool, I'll look into this then. I've already fixed one of them and made it work. So applying that to all the other apps should be doable.

**Comment by marcelkalveram** [comment]
@GantMan I realised this has to be done step by step, since each repo has a different RN setup (some are based on Expo, and RN versions also vary). So if it's fine with you, I'll submit one PR per folder. Let me keep track here of the progress using a task list. First PR coming soon :)

- [ ] ApolloLinkState
- [ ] AppSync
- [ ] Context
- [ ] Freactal
- [ ] MobX
- [ ] MobXStateTree
- [ ] ReactAutomata
- [ ] ReactEasyState
- [ ] ReactObservableStore
- [ ] Redux
- [ ] ReduxX
- [ ] Rematch
- [ ] Unistore
- [ ] Unstated 
- [ ] immer
- [ ] microstates
- [ ] pure-store
- [ ] react-recontext
- [ ] react-simplified
- [ ] setState
- [ ] simple-remx

**Comment by GantMan** [comment]
Awesome contributions Marcel

**Comment by marcelkalveram** [comment]
@GantMan thanks! I've checked off above the ones that are done. I'll submit a few more PPs in the next couple of days.

**Comment by marcelkalveram** [comment]
Half way there, however `react-easy-state` and `react-simplified` turned out to be slightly more tricky, because of issues with the Android JSC and some xCode-related tests. 

I'll look into this when I have more time. In the meantime, I'll continue updating the "easy" ones.

**Comment by marcelkalveram** [comment]
@GantMan I think this can be closed now 👍

**Comment by GantMan** [comment]
![finally](https://user-images.githubusercontent.com/997157/56306381-ec61ab80-6107-11e9-808e-ca421ced7973.gif)
