### ISSUE TITLE
Remove reduxx

### ISSUE THREAD

**Issue by StevenLangbroek** [GantMan/ReactStateMuseum#140]
There should be no place in any of our communities for people like this:

![image](https://user-images.githubusercontent.com/296796/64967649-34485280-d8a1-11e9-98be-c70235bae622.png)

**Comment by StevenLangbroek** [comment]
More:

![image](https://user-images.githubusercontent.com/296796/64967753-5e9a1000-d8a1-11e9-90e3-07088e9d7397.png)

**Comment by arackaf** [comment]
Seconded. Please purge this library. For the good of the community.

**Comment by msteckyefantis** [comment]
I love everyone here, it was pleasure writing the tests for library that are still here🥰

Thanks for checking out ReduxX, the next generation React state management library!❤️

https://github.com/msteckyefantis/reduxx

You are also sexy and sensual men🥰

**Comment by msteckyefantis** [comment]
I love everyone here, it was pleasure writing the tests for this repo that are still here🥰

Thanks for checking out ReduxX, the next generation React state management library!❤️

https://github.com/msteckyefantis/reduxx

You are also sexy and sensual men🥰

**Comment by msteckyefantis** [comment]
Every time you run the tests for this library, you are supporting my cause, so thanks for that.

I really do love you sensual men.❤️

**Comment by msteckyefantis** [comment]
Here is some reading material:

https://medium.com/@mikeysteckyefantis/maybe-its-time-to-start-systematically-ridding-our-society-of-bad-men-5527f56c2d08

It's a plan to help the women in our society.

**Comment by msteckyefantis** [comment]
Please feel free to share my plan with the world like you already have with ReduxX - the next generation React state management library!

Once again, I really do love you sensual men.🥰Thanks again so much for everything.❤️
