### ISSUE TITLE
Add ReactObservableStore example

### ISSUE THREAD

**Issue by taviroquai** [GantMan/ReactStateMuseum#17]
Hello,

It is possible to add ReactObservableStore please?
https://github.com/taviroquai/ReactObservableStore

If so, please tell me what I need to do.

Cheers

**Comment by GantMan** [comment]
Yes of course!  Please PR the example.  If you're uncomfortable doing both React and React Native, just deliver one of them (with the same structure as others) and I'll convert it to the other.

**Comment by taviroquai** [comment]
@GantMan 
Thanks again. Although, I did not add it to the README. Can you please do this? Cheers.
