### ISSUE TITLE
Add Apollo Link State example

### ISSUE THREAD

**Issue by juandc** [GantMan/ReactStateMuseum#19]
There is a GraphQL option to manage state in a central store and _render props_ with [Apollo link state](https://github.com/apollographql/apollo-link-state). I also have a presentation (_not mine obviously_): [Link state is dope](https://link-state-is-dope.now.sh).

So, may I send a PR for React?

**Comment by juandc** [comment]
Its done, this issue can be closed :+1:

**Comment by GantMan** [comment]
I'm gonna make a React Native version to companion it and then close :)

**Comment by juandc** [comment]
Ohh yess... :sweat_smile:

**Comment by juandc** [comment]
- Package Json description is wrong
 - README is inside `src/`

Solved by #31

**Comment by GantMan** [comment]
@juandc - after further examination.  Is this really using apollo-link-state or is it just using apollo?

I don't even see the module for https://github.com/apollographql/apollo-link-state

I think we might need to rename this example.

**Comment by juandc** [comment]
Hmmm ... Not sure ...
The `apollo-boost` package is a container package for:` apollo-client`, `apollo-cache-inmemory`,` apollo-link-http`, `apollo-link-error`, **`apollo-link-state`** and` graphql-tag`.

In this case I think this is an example of apollo-link-state because we are not using any other apollo feature; but rename it to just apollo would not be a bad idea any way :+1:

**Comment by GantMan** [comment]
I don't see you calling `withClientState` anywhere, though.  I might just be ignorant, heh.  I've never used it, but I would have expected to see it given what I read here:  https://github.com/apollographql/apollo-link-state

**Comment by juandc** [comment]
That is the `apollo-boost` package advantage! You don't need to use `withClientState` or any other apollo-package config rule unless you want ([Apollo Boost Migration](https://www.apollographql.com/docs/react/advanced/boost-migration.html#advanced-migration)); you can use the config helpers (like `clientState` for `withClientState`) and make your config easier to read and write :grinning: .

**Comment by juandc** [comment]
https://github.com/juandc/ReactStateMuseum/blob/d983afe06c5da77864f8dfd2bc0e12e9205fad1d/React/apollo-link-state/src/store/client.js#L8

**Comment by amerani** [comment]
i'm claiming the react native example for apollo-link-state

**Comment by juandc** [comment]
@amerani You are a Hero! :muscle:

**Comment by GantMan** [comment]
finished off in #78
