### ISSUE TITLE
Add Jotai

### ISSUE THREAD

**Issue by jalalbmnf** [GantMan/ReactStateMuseum#344]
Website : https://jotai.org/
Repository : https://github.com/pmndrs/jotai

I want to work on this issue :)

**Comment by GantMan** [comment]
please do!  It will be added.

**Comment by jalalbmnf** [comment]
@GantMan please review my PR #345, any feedback welcome 👍🏼

**Comment by GantMan** [comment]
Looks fantastic!  merged 👍
