### ISSUE TITLE
Awesome integration tests

### ISSUE THREAD

**Issue by GantMan** [GantMan/ReactStateMuseum#37]
A single command to make sure all examples work, and that if they have tests that they pass.

It could also check the Readme to make sure there are no missing links.

Sounds like some basic JavaScript and good first issue.

**Comment by msteckyefantis** [comment]
hello GMan,

I can put a bit of work into this this weekend, as long as I get specific instructors of what needs to be done.

**Comment by GantMan** [comment]
## Sure!  Should be easy in 2 parts

### Part 1
Thinking like a shell script.  If it could list each folder, CD into each and run `yarn && yarn build && CI=true yarn test` expecting an exit code of 0 for the result.  It's not hard to do with a shell script but the [execa](https://github.com/sindresorhus/execa) package lets us do this in official JS testing.

If any folder fails, then we know that it's been broken.  This will help with managing the vast libs through PRs.

### Part 2
The second part would be to make sure that each folder has been mentioned on the readme:
```
// Something like this with fs-jetpack
test('Verify each folder has a link in readme', () => {
   const folders = jetpack.ls('./React')
   const readmeContents = jetpack.read(`README.md`)
   folders.map(folderName => {
     expect(readmeContents.includes(fodlerName)).toBe(true)
   })
})
```

The second part is just sugar... but would be cool to make sure we don't miss anything.  Let me know if there's any questions 👍

**Comment by msteckyefantis** [comment]
Alright, I am a [mocha](https://mochajs.org)/[chai expect](http://www.chaijs.com/api/bdd/)/[proxyquire](https://www.npmjs.com/package/proxyquire)/[sinon](http://sinonjs.org/) guy, it's literally puts food on the plate for me🍱.

but I will also look into the tools you mentioned, I am also good working with child processes, so I can make it work in node, np bruv👍

**Comment by msteckyefantis** [comment]
Starting to work on the tests,

putting them in a folder called `test` on the root level, let me know if you want me to put them somewhere else.

**Comment by GantMan** [comment]
Looks great! Thanks for taking this on.

**Comment by msteckyefantis** [comment]
sorry got distracted by 🐈will finish this and take this on asap, got a hike with my parents this morning, but still this is my priority😬, I got your back, I will get this tested👌.

**Comment by msteckyefantis** [comment]
[https://github.com/GantMan/ReactStateMuseum/pull/55](Added the Readme test), made a note of the fact that currently not all of the links are included.

About the other tests, I haven't done them yet, but I did try running the command you suggested on a few of the libraries. They did not pass that test, is that command the best way to test the libraries?

**Comment by GantMan** [comment]
@msteckyefantis - excellent!  The tests are catching issues already!  Hehe.

as for `yarn && yarn build && CI=true yarn test` - I just ran that in React/context and it worked fine.  I bet it will work for anything in the `React/` folders.

For `ReactNative/` we can run these two commands:

```
react-native bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output ./ios/main.jsbundle --assets-dest ./ios/release/main.jsbundle
```
AND
```
react-native bundle --entry-file index.js --platform android --dev false --reset-cache --bundle-output ./android/main.jsbundle --assets-dest ./android/app/build/main.jsbundle
```

This will bundle for iOS and on Android.  Basically the equivalent of `yarn build`


There can even be an extra step on Android (which won't work on most CI) where we do an actual build of the APK
```
cd android && ./gradlew assembleRelease && cd -
```

Let me know if this helps.

**Comment by msteckyefantis** [comment]
[added the react test](https://github.com/msteckyefantis/ReactStateMuseum/tree/master/test)

here are the results:
```
... I am running the test now, will put there here when the test finishes👌
```

**Comment by GantMan** [comment]
lol.  Poor reduxX.  -  so it looks like it's not transpiled?

btw, I just fixed `mobx-state-tree` in master

**Comment by GantMan** [comment]
Tests are already fixing things!!!!

**Comment by msteckyefantis** [comment]
About ReduxX, nah, my code is always OG JS.

What's the best way to transpile it? Thanks.

**Comment by GantMan** [comment]
Go with either Babel or TypeScript.   Both will transpile down to ES5 super easy.

I'm a fan of TypeScript, bc I like their static type checking etc.   You end up with a `/src` where your readable code lives, and a `/dist` where your ES5 lives right before you publish to NPM.  Here's a project I maintain that uses TypeScript:  https://github.com/infinitered/solidarity

I understand if you say, "Nope, I don't need all that types stuff" and just go with a nice babel setup.  But I dare say I've done both, and TS is my fav.

**Comment by GantMan** [comment]
coming soon the transpile museum!  just joking!!!  😆

**Comment by msteckyefantis** [comment]
Thanks for the info, I've used Babel before when webpacking sites, but I've never used it for regular npm packages, I'll figure that out, will also look into Typescript. Also fyi, I will be able to do the React Native tests by the weekend👍.

**Comment by msteckyefantis** [comment]
(update: got delayed due to being on a company trip, I was expecting there to be wifi on the plane ride, sorry, will push it asap, i wrote most of the code already)

**Comment by GantMan** [comment]
sweet!  ran the code yesterday!~  looking forward to it!

**Comment by msteckyefantis** [comment]
Added the [React Native Tests](https://github.com/GantMan/ReactStateMuseum/pull/64)👩🏽‍🔬

**Comment by GantMan** [comment]
Great work @msteckyefantis - closing this ticket now.
