### ISSUE TITLE
Add allcontibutors script

### ISSUE THREAD

**Issue by GantMan** [GantMan/ReactStateMuseum#38]
I'm a fan of adding this to every project.   

https://github.com/kentcdodds/all-contributors

**Comment by tyler-reitz** [comment]
I'd like to try and tackle this. Should it be entirely automated (if possible) or would you be handling the upkeep and maintenance of the list and adding contributors?

**Comment by GantMan** [comment]
The cli is awesome.  It helps you but is not automated 100%

Basically we put it in place and I update it using the cli

**Comment by tyler-reitz** [comment]
Ok, ya just read the notes for repository maintainers from the spec that details updating. Also, just opened a PR for this—which is literally my second PR ever—so let me know if there's anything that's wrong or needs cleaning up.
