### ISSUE TITLE
Add Rematch example

### ISSUE THREAD

**Issue by juandc** [GantMan/ReactStateMuseum#39]
[Rematch](https://rematch.gitbooks.io/rematch/#examples) is a simpler alternative to Redux. It uses `react-redux` for connecting react with rematch :stuck_out_tongue_closed_eyes:. Works fine with [`redux-devtools`](https://rematch.gitbooks.io/rematch/docs/recipes/devtools.html).

Comparison with Redux (taken from the [purpose](https://rematch.gitbooks.io/rematch/docs/purpose.html)) page:
<table>
<thead>
<tr>
<th></th>
<th>Redux</th>
<th>Rematch</th>
</tr>
</thead>
<tbody>
<tr>
<td>simple setup ‎</td>
<td></td>
<td>‎✔</td>
</tr>
<tr>
<td>less boilerplate</td>
<td></td>
<td>‎✔</td>
</tr>
<tr>
<td>readability</td>
<td></td>
<td>‎✔</td>
</tr>
<tr>
<td>configurable</td>
<td>‎✔</td>
<td>‎✔</td>
</tr>
<tr>
<td>redux devtools</td>
<td>‎✔</td>
<td>‎✔</td>
</tr>
<tr>
<td>generated action creators</td>
<td>‎</td>
<td>‎✔</td>
</tr>
<tr>
<td>global dispatch</td>
<td>‎</td>
<td>‎✔</td>
</tr>
<tr>
<td>async</td>
<td>thunks</td>
<td>‎async/await</td>
</tr>
</tbody>
</table>

PR?

**Comment by GantMan** [comment]
Sweet!  Yes!  I can't wait to see this one.

**Comment by GantMan** [comment]
close via #46 and #50

**Comment by juandc** [comment]
Also you can celebrate the 100 commit in the repo :tada:
