### ISSUE TITLE
Should I add this comic?

### ISSUE THREAD

**Issue by GantMan** [GantMan/ReactStateMuseum#48]
![image](https://user-images.githubusercontent.com/997157/40189816-f23c5b10-59c2-11e8-96b1-fcfb0ca51d4a.png)

Or would everyone get angry?  😸

**Comment by juandc** [comment]
Add it!!!! :tada: :joy:

**Comment by DanielZlotin** [comment]
Please do

**Comment by GantMan** [comment]
Comic was added!
