### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nunojesus** [GantMan/ReactStateMuseum#67]
Hi, first congrats for your project.
I like to contribute with graphic designs, in opensource projects, so if you need something from me like a logotype or something else just say it, Im here ready to help you.
Greetings!
Nuno Jesus

**Comment by GantMan** [comment]
**That's so awesome!**  I wish I had you before I got my silly Museum logo at the top.

Not sure there's more graphically that could be contributed, but I might refer you to some other burgeoning projects if that's cool?  Open to suggestions, but currently sitting pretty on design, (unless you see something I could improve).

**Comment by GantMan** [comment]
BTW, I just checked your past work!  You're very talented!

**Comment by nunojesus** [comment]
Thanks for your words! Do you have any request for the logo? 
Greetings!
Nuno Jesus

**Comment by nunojesus** [comment]
Hello, I create this designs for your project, see if you like one of this logos or not.

Greetings!

![myseum](https://user-images.githubusercontent.com/34600369/41381640-9fa6553c-6f60-11e8-8af3-5a7a8c9c9e4f.png)

**Comment by juandc** [comment]
All are AWESOME!
But I like the last 2 :thinking:

**Comment by GantMan** [comment]
I'm thinking the bottom left (purple).  It's great looking large and small.

**Comment by nunojesus** [comment]
Hello, Im happy that you like one, so now I will create the files to send to you, what color do you want?

Greetings!

Nuno Jesus

**Comment by GantMan** [comment]
Can I see it in purple, blue, and red?  One of those 3 is best.

**Comment by nunojesus** [comment]
![myseum](https://user-images.githubusercontent.com/34600369/41485792-dcfb6cea-70d9-11e8-8a85-4f322f0b68f1.png)

**Comment by GantMan** [comment]
![image](https://user-images.githubusercontent.com/997157/41488988-f0afb348-70b3-11e8-8fa4-4a82f83b7d0c.png)

Going with this one, plz send graphics for that.

**Comment by nunojesus** [comment]
Nice, what files do you want? png and svg files?

**Comment by GantMan** [comment]
PERFECT!!!!!

**Comment by nunojesus** [comment]
I will send you tomorrow, ok?

Greetings!

**Comment by GantMan** [comment]
THANKS!
