### ISSUE TITLE
React/mobx example does not compile

### ISSUE THREAD

**Issue by cowboyd** [GantMan/ReactStateMuseum#9]
After a `yarn && yarn start`

```
Failed to compile.

./src/Components/addItem.js
Syntax error: Unexpected token (6:0)

  4 | import { observer } from "mobx-react";
  5 |
> 6 | @observer
    | ^
  7 | export default class AddItems extends Component {
  8 |   render() {
  9 |     return (

❯❯❯❯ node -v                                                                                                                                                                       ~/C/J/R/R/mobx master
v9.11.1
❯❯❯❯ yarn --version                                                                                                                                                                ~/C/J/R/R/mobx master
1.5.1
```

**Comment by GantMan** [comment]
Graet ticket:  For some reason the sandbox with the exact same code works:  https://codesandbox.io/s/github/GantMan/ReactStateMuseum/tree/master/React/mobx

So I'm trying to figure out what I'm missing... they both use the same code.  I'll see if I can call in some help here.  React web is second to my React Native experience.

**Comment by GantMan** [comment]
Looks like somehow Sandbox was working regardless, but no worries, I think I just have to eject:
https://medium.com/@rodcisal/ejecting-and-adding-decorator-support-to-your-create-react-app-a4a7d80e4077

I'll test this and let you know how it works out.

**Comment by GantMan** [comment]
Glad this is fixed now!  Thanks for the ticket!
