### ISSUE TITLE
Simplify setState

### ISSUE THREAD

**Issue by GantMan** [GantMan/ReactStateMuseum#93]
setState doesn't need to store functions in state.

### Remove
https://github.com/GantMan/ReactStateMuseum/blob/master/React/setState/src/index.js#L25-L26

&&

https://github.com/GantMan/ReactStateMuseum/blob/master/ReactNative/setState/App.js#L17-L18

**Comment by durangatan** [comment]
Hi! Mind if I work on this? It came up when I was looking for React Hacktoberfest issues to work on.

**Comment by GantMan** [comment]
@durangatan - all yours!  Congrats!

**Comment by GantMan** [comment]
Ideally, I'd love for you to move state to just this
```js
  state = {
    allItems: ["nachos", "burritos", "hot dog"],
    newItemName: ""
  };
```
